// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {category} from '../models';
import {context} from '../models';

export function ArchiveCategory(arg1:category.GetCategoryByIdInput):Promise<void>;

export function CreateCategory(arg1:category.CreateCategoryInput):Promise<category.Category>;

export function GetAllCategories(arg1:category.GetAllCategoriesInput):Promise<category.GetAllCategoriesResult>;

export function GetCategoryById(arg1:category.GetCategoryByIdInput):Promise<category.Category>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpdateCategory(arg1:category.UpdateCategoryInput):Promise<category.Category>;
