// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveCategory(arg1) {
  return window['go']['category']['CategoryApi']['ArchiveCategory'](arg1);
}

export function CreateCategory(arg1) {
  return window['go']['category']['CategoryApi']['CreateCategory'](arg1);
}

export function GetAllCategories(arg1) {
  return window['go']['category']['CategoryApi']['GetAllCategories'](arg1);
}

export function GetCategoryById(arg1) {
  return window['go']['category']['CategoryApi']['GetCategoryById'](arg1);
}

export function SetContext(arg1) {
  return window['go']['category']['CategoryApi']['SetContext'](arg1);
}

export function UpdateCategory(arg1) {
  return window['go']['category']['CategoryApi']['UpdateCategory'](arg1);
}
