// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateUnit(arg1) {
  return window['go']['unit']['UnitApi']['CreateUnit'](arg1);
}

export function GetAllUnits(arg1) {
  return window['go']['unit']['UnitApi']['GetAllUnits'](arg1);
}

export function GetUnitById(arg1) {
  return window['go']['unit']['UnitApi']['GetUnitById'](arg1);
}

export function SetContext(arg1) {
  return window['go']['unit']['UnitApi']['SetContext'](arg1);
}

export function UpdateUnit(arg1) {
  return window['go']['unit']['UnitApi']['UpdateUnit'](arg1);
}
