// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {unit} from '../models';
import {context} from '../models';

export function CreateUnit(arg1:unit.CreateUnitInput):Promise<unit.Unit>;

export function GetAllUnits(arg1:unit.GetAllUnitsInput):Promise<unit.GetAllUnitsResult>;

export function GetUnitById(arg1:unit.GetUnitByIdInput):Promise<unit.Unit>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpdateUnit(arg1:unit.UpdateUnitInput):Promise<unit.Unit>;
