// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProduct(arg1) {
  return window['go']['product']['ProductApi']['CreateProduct'](arg1);
}

export function GetAllProducts(arg1) {
  return window['go']['product']['ProductApi']['GetAllProducts'](arg1);
}

export function GetProductById(arg1) {
  return window['go']['product']['ProductApi']['GetProductById'](arg1);
}

export function SetContext(arg1) {
  return window['go']['product']['ProductApi']['SetContext'](arg1);
}
