// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBalancesByProductID(arg1) {
  return window['go']['inventory']['InventoryApi']['GetBalancesByProductID'](arg1);
}

export function GetInventoryBalance(arg1) {
  return window['go']['inventory']['InventoryApi']['GetInventoryBalance'](arg1);
}

export function GetInventoryMovements(arg1) {
  return window['go']['inventory']['InventoryApi']['GetInventoryMovements'](arg1);
}

export function GetLowStockProducts(arg1) {
  return window['go']['inventory']['InventoryApi']['GetLowStockProducts'](arg1);
}

export function GetMovementsByProductID(arg1) {
  return window['go']['inventory']['InventoryApi']['GetMovementsByProductID'](arg1);
}

export function SetContext(arg1) {
  return window['go']['inventory']['InventoryApi']['SetContext'](arg1);
}
