// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {inventory} from '../models';
import {context} from '../models';

export function GetBalancesByProductID(arg1:inventory.GetBalancesByProductIDInput):Promise<Array<inventory.InventoryBalance>>;

export function GetInventoryBalance(arg1:inventory.GetInventoryBalanceInput):Promise<inventory.InventoryBalance>;

export function GetInventoryMovements(arg1:inventory.GetMovementsInput):Promise<inventory.GetMovementsResult>;

export function GetLowStockProducts(arg1:inventory.GetLowStockInput):Promise<inventory.GetLowStockResult>;

export function GetMovementsByProductID(arg1:inventory.GetMovementsInput):Promise<inventory.GetMovementsResult>;

export function SetContext(arg1:context.Context):Promise<void>;
